version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: furniture-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: furnituredb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: furniture-app
    container_name: furniture-backend
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: furniture-02
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/furnituredb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SERVER_PORT: 8081
      SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 20MB
      SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 100MB

volumes:
  mysql_data:
